# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20170518_1527'),
    ]

    operations = [
    ]
